name: autoapi

on:
  push:
    branches:
      - master

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: dandomate/autoapi

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Compile AutoApiApplication
        run: mvn compile
      - name: Test AutoApiApplication
        run: mvn test
      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.AUTOAPI_SECRET }}
        run: mvn --batch-mode deploy -s .github/settings.xml
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.AUTOAPI_SECRET }}
      - name: Build and push Docker image
        run: |
          docker build . -t ${{ env.DOCKER_REGISTRY }}/dandomate/autoapi:0.0.2-snapshot
          docker push ${{ env.DOCKER_REGISTRY }}/dandomate/autoapi:0.0.2-snapshot
